### ISSUE TITLE
Maven coords?

### ISSUE THREAD

**Issue by adorokhine** [jfree/skijagraphics2d#3]
Hello, I'm interested in using this project but I don't see any maven repo coordinates or binaries for it. Could you upload it to maven central?

**Comment by jfree** [comment]
I didn't upload to Maven Central yet because I needed to find out how to deal with the platform specific dependency on Skija (you'll see in the pom.xml that I have a dependency on the Mac version which I am using).  There is some discussion about it in https://github.com/jfree/skijagraphics2d/issues/1

For now, you can clone the repo and build it locally, but I should get it uploaded to Maven Central before too long.

**Comment by jfree** [comment]
It should be there now:

<dependency>
        <groupId>org.jfree</groupId>
        <artifactId>org.jfree.skijagraphics2d</artifactId>
        <version>1.0.0</version>
    </dependency>

Let me know if it works OK with respect to the different platform specific Skija dependencies.
